### ISSUE TITLE
6.2 As a user	I want to be able to see all my saved discussion boards	so that i can easily view my saved content

### ISSUE THREAD

**Issue by nsood1** [saakethkoka/ChildcareForum#19]
Size 13

Given a user wants to see their saved discussion boards, when a user visits a favorited boards page, then all that user's favorited boards should be displayed

Given a user visits their saved boards page, when the user has no favorited boards, then the page should explain to the user they can favorite boards they like to view later on this page

Given a user wants to see their saved discussion boards, when a user visits a favorited boards page, then all that user's favorited boards should be listed by categories defined by the user

**Comment by BradfordSigety** [comment]
Completed GET for all saved posts for a specific user
