### ISSUE TITLE
4.3 As a user I want to filter my search results by verified users only so that I can trust the integrity of the discussion

### ISSUE THREAD

**Issue by BradfordSigety** [saakethkoka/ChildcareForum#26]
Relevant Size - 8
Acceptance Criteria
- Given a user wants to filer their results by verified, when the user adds the verified user filter, only posts made by verified users will be in search results
- Given a user wants to filer their results by verified, when the user adds the verified user filter, if there is no verified posts related to keyword, there will be no search results

**Comment by nsood1** [comment]
api for this has been written. 

it is called /verifiedpostusers
