### ISSUE TITLE
4.1 As a user I want to search for specific keywords so that I can see relevant posts to the topic I want to know more about

### ISSUE THREAD

**Issue by BradfordSigety** [saakethkoka/ChildcareForum#9]
Relevant Size - 21
Acceptance Criteria
- Given a user wants to search keywords, when the user enters a search with an unknown keyword, the user is presented with no results.
- Given a user wants to search keywords, when the user enters a viable keyword, the user is presented with relevant results
- Given a user wants to search keywords, when the user enters a irrelevant keyword, the user is presented with no relevant results

**Comment by nsood1** [comment]
api to filter by key word word has been written. 

it is called /searchposts

it takes in one key word and will return any discussion post which contains that. If no word is passed in then it will return the whole dataset.
